/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ebercruz.myrluxb.deepseek.api.contract;

import com.ebercruz.myrluxb.deepseek.api.model.LLMRequest;
import com.ebercruz.myrluxb.deepseek.api.model.ModelApiResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-01-27T19:54:12.066667-06:00[America/Mexico_City]")
@Validated
@Tag(name = "LLM", description = "Operaciones con el modelo de lenguaje")
public interface LlmApi {

    /**
     * POST /llm/chat : Genera una respuesta de chat
     * Endpoint unificado que maneja tanto streaming como respuestas completas
     *
     * @param llMRequest  (required)
     * @return Respuesta exitosa (status code 200)
     *         or  (status code 400)
     *         or  (status code 404)
     *         or  (status code 500)
     */
    @Operation(
        operationId = "chat",
        summary = "Genera una respuesta de chat",
        description = "Endpoint unificado que maneja tanto streaming como respuestas completas",
        tags = { "LLM" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Respuesta exitosa", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class)),
                @Content(mediaType = "text/event-stream", schema = @Schema(implementation = ModelApiResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class)),
                @Content(mediaType = "text/event-stream", schema = @Schema(implementation = ModelApiResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class)),
                @Content(mediaType = "text/event-stream", schema = @Schema(implementation = ModelApiResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class)),
                @Content(mediaType = "text/event-stream", schema = @Schema(implementation = ModelApiResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/llm/chat",
        produces = { "application/json", "text/event-stream" },
        consumes = { "application/json" }
    )
    
    default Mono<ResponseEntity<ModelApiResponse>> _chat(
        @Parameter(name = "LLMRequest", description = "", required = true) @Valid @RequestBody Mono<LLMRequest> llMRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        return chat(llMRequest, exchange);
    }

    // Override this method
    default  Mono<ResponseEntity<ModelApiResponse>> chat(Mono<LLMRequest> llMRequest,  final ServerWebExchange exchange) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"code\" : \"code\", \"success\" : true, \"message\" : \"message\", \"errors\" : [ \"errors\", \"errors\" ] }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
            if (mediaType.isCompatibleWith(MediaType.valueOf("text/event-stream"))) {
                String exampleString = "Custom MIME type example not yet supported: text/event-stream";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf(""), exampleString);
                break;
            }
        }
        return result.then(llMRequest).then(Mono.empty());

    }

}
