/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ebercruz.myrluxb.deepseek.api.contract;

import com.ebercruz.myrluxb.deepseek.api.model.HealthResponse;
import com.ebercruz.myrluxb.deepseek.api.model.LivenessResponse;
import com.ebercruz.myrluxb.deepseek.api.model.MetricsResponse;
import com.ebercruz.myrluxb.deepseek.api.model.ModelApiResponse;
import com.ebercruz.myrluxb.deepseek.api.model.ReadinessResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-01-27T19:54:12.066667-06:00[America/Mexico_City]")
@Validated
@Tag(name = "Monitoring", description = "Endpoints de monitoreo y salud del servicio")
public interface MonitoringApi {

    /**
     * GET /actuator/metrics : Obtiene las métricas del servicio
     * Proporciona métricas detalladas sobre el rendimiento y uso del servicio
     *
     * @return Métricas del servicio (status code 200)
     */
    @Operation(
        operationId = "getMetrics",
        summary = "Obtiene las métricas del servicio",
        description = "Proporciona métricas detalladas sobre el rendimiento y uso del servicio",
        tags = { "Monitoring" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Métricas del servicio", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MetricsResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/actuator/metrics",
        produces = { "application/json" }
    )
    
    default Mono<ResponseEntity<MetricsResponse>> _getMetrics(
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        return getMetrics(exchange);
    }

    // Override this method
    default  Mono<ResponseEntity<MetricsResponse>> getMetrics( final ServerWebExchange exchange) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"measurements\" : [ { \"name\" : \"name\", \"measurements\" : [ { \"statistic\" : \"statistic\", \"value\" : 0.8008281904610115 }, { \"statistic\" : \"statistic\", \"value\" : 0.8008281904610115 } ] }, { \"name\" : \"name\", \"measurements\" : [ { \"statistic\" : \"statistic\", \"value\" : 0.8008281904610115 }, { \"statistic\" : \"statistic\", \"value\" : 0.8008281904610115 } ] } ] }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(Mono.empty());

    }


    /**
     * GET /actuator/prometheus : Endpoint de métricas para Prometheus
     * Expone métricas en formato Prometheus
     *
     * @return Métricas en formato Prometheus (status code 200)
     */
    @Operation(
        operationId = "getPrometheusMetrics",
        summary = "Endpoint de métricas para Prometheus",
        description = "Expone métricas en formato Prometheus",
        tags = { "Monitoring" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Métricas en formato Prometheus", content = {
                @Content(mediaType = "text/plain", schema = @Schema(implementation = String.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/actuator/prometheus",
        produces = { "text/plain" }
    )
    
    default Mono<ResponseEntity<String>> _getPrometheusMetrics(
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        return getPrometheusMetrics(exchange);
    }

    // Override this method
    default  Mono<ResponseEntity<String>> getPrometheusMetrics( final ServerWebExchange exchange) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        return result.then(Mono.empty());

    }


    /**
     * GET /actuator/health : Verifica el estado general del servicio
     * Proporciona información detallada sobre el estado del servicio y sus dependencias
     *
     * @return Estado del servicio (status code 200)
     *         or  (status code 503)
     */
    @Operation(
        operationId = "healthCheck",
        summary = "Verifica el estado general del servicio",
        description = "Proporciona información detallada sobre el estado del servicio y sus dependencias",
        tags = { "Monitoring" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Estado del servicio", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = HealthResponse.class))
            }),
            @ApiResponse(responseCode = "503", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/actuator/health",
        produces = { "application/json" }
    )
    
    default Mono<ResponseEntity<HealthResponse>> _healthCheck(
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        return healthCheck(exchange);
    }

    // Override this method
    default  Mono<ResponseEntity<HealthResponse>> healthCheck( final ServerWebExchange exchange) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"components\" : { \"diskSpace\" : { \"details\" : { \"key\" : \"\" }, \"status\" : \"UP\" }, \"ollama\" : { \"details\" : { \"key\" : \"\" }, \"status\" : \"UP\" }, \"db\" : { \"details\" : { \"key\" : \"\" }, \"status\" : \"UP\" } }, \"status\" : \"UP\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(Mono.empty());

    }


    /**
     * GET /actuator/health/liveness : Verifica si el servicio está vivo
     * Endpoint para Kubernetes liveness probe
     *
     * @return Servicio vivo (status code 200)
     *         or  (status code 503)
     */
    @Operation(
        operationId = "livenessCheck",
        summary = "Verifica si el servicio está vivo",
        description = "Endpoint para Kubernetes liveness probe",
        tags = { "Monitoring" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Servicio vivo", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LivenessResponse.class))
            }),
            @ApiResponse(responseCode = "503", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/actuator/health/liveness",
        produces = { "application/json" }
    )
    
    default Mono<ResponseEntity<LivenessResponse>> _livenessCheck(
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        return livenessCheck(exchange);
    }

    // Override this method
    default  Mono<ResponseEntity<LivenessResponse>> livenessCheck( final ServerWebExchange exchange) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"status\" : \"UP\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(Mono.empty());

    }


    /**
     * GET /actuator/health/readiness : Verifica si el servicio está listo para recibir tráfico
     * Endpoint para Kubernetes readiness probe
     *
     * @return Servicio listo (status code 200)
     *         or  (status code 503)
     */
    @Operation(
        operationId = "readinessCheck",
        summary = "Verifica si el servicio está listo para recibir tráfico",
        description = "Endpoint para Kubernetes readiness probe",
        tags = { "Monitoring" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Servicio listo", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ReadinessResponse.class))
            }),
            @ApiResponse(responseCode = "503", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ModelApiResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/actuator/health/readiness",
        produces = { "application/json" }
    )
    
    default Mono<ResponseEntity<ReadinessResponse>> _readinessCheck(
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        return readinessCheck(exchange);
    }

    // Override this method
    default  Mono<ResponseEntity<ReadinessResponse>> readinessCheck( final ServerWebExchange exchange) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"status\" : \"UP\", \"dependencies\" : { \"database\" : \"UP\", \"ollama\" : \"UP\" } }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(Mono.empty());

    }

}
