version: '3.8'

services:
  app:
    build: .
    ports:
      - "11002:11002"
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/schoolbd
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - myrlux-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11002/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:latest
    ports:
      - "5434:5432"  # Cambiado a 5434 para evitar conflictos
    environment:
      - POSTGRES_DB=schoolbd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - myrlux-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  myrlux-network:
    driver: bridge