logging:
  pattern:
    console: "[Myrlux-Backend] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: INFO
    com.ebercruz.myrlux: DEBUG
    org:
      springframework:
        web: DEBUG
        data: DEBUG
        transaction: DEBUG
        orm.jpa: DEBUG
    reactor:
      netty: DEBUG
      core: DEBUG
    io:
      netty: DEBUG

server:
  port: 11002
  ssl:
    protocols: false
  error:
    whitelabel:
      enabled: false
      include-stacktrace: never

spring:
  application:
    name: myrlux-back
    description: Una aplicación de ejemplo
    api-path: /api
  mvc:
    log-resolved-exception: false
  datasource:
    url: jdbc:postgresql://localhost:5432/schoolbd
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  codec:
    max-in-memory-size: 500MB
  main:
    banner-mode: OFF
  devtools:
    restart:
      additional-paths:
        - conf/**

springdoc:
  show-actuator: true
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  use-management-port: false
  use-root-path: true

management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

api:
  web:
    clients:
      login:
        post:

cloud:
  config:
    discovery:
      enabled: false